### ISSUE TITLE
Not working in Noetic

### ISSUE THREAD

**Issue by rlabs-oss** [Livox-SDK/livox_mapping#11]
Would it be possible to update the the source code to include a version for ROS Noetic? Or please advise how to build it using Ubuntu 20.04 and ROS Noetic.

**Comment by Ab-Tx** [comment]
It's possible to change a few things in the source code just so it barely works with Noetic Ubuntu 20.04.

On the source code, search in the files for "frame" and replace
`"/livox"` for `"livox"`
and also
`"/camera_init"` for `"camera_init"`

The opencv header has to be changed also. Change
`#include <opencv/cv.h>` to `#include "opencv2/imgproc/imgproc.hpp"`

On the "loam_livox.rviz" file, **do not** replace `/camera_init` by `camera_init`.
