### ISSUE TITLE
Noetic support?

### ISSUE THREAD

**Issue by rlabs-oss** [Livox-SDK/livox_mapping#12]
Updating the opencv headers and building for ROS Noetic I do not see the pointcloud scan at all. - rviz is blank. The pose information will change if the lidar is moved. Fixed frame camera_init is not present and returns errors in rviz. Using pointcloud2 and /livox/lidar the scan is visible which indicates the lidar is working. 

Do you have a version which works with ROS Noetic?

**Comment by fjc378209410** [comment]
Hello, is your problem solved?

**Comment by rlabs-oss** [comment]
> Hello, is your problem solved?
No.

**Comment by rlabs-oss** [comment]
Closed due to lack of response

**Comment by yorklyb** [comment]
Check this out:
https://github.com/York-SDCNLab/m_livox_mapping
