### ISSUE TITLE
How to dye Cloudpoins in real time based on this project.

### ISSUE THREAD

**Issue by alsosos** [Livox-SDK/livox_mapping#14]
The calibration of lidar and camera has been done and  the Cloudpoints dyeing after collecting point of cloud  and image respectively is realized.How to combine two projects to realize real-time Cloudpoints coloring,thanks~

**Comment by Livox-SDK** [comment]
Hi alsosos,
TBH, that's a great idea. We may make some improvements in the future. For now we are focusing on helping everyone getting start with Livox Lidar easily.
