### ISSUE TITLE
Play mid40_ oudor bag, the point cloud will not move, as if there is only one frame of data. How can I solve this problem

### ISSUE THREAD

**Issue by alsosos** [Livox-SDK/livox_mapping#15]
And i directly run mid-40 launch ,then only display one frmae cloudpoints data.

**Comment by alsosos** [comment]
Can this project support pcl1.11

**Comment by loerss** [comment]
您好，我也遇到这个问题了，rviz里面只显示白色的第一帧数据，没办法建图，请问您有什么解决办法吗

**Comment by Livox-SDK** [comment]
Hi alsosos, loerss
Would you mind also sharing the detail information of environment you are using for running this code? Such as Linux version, Eigen version, OpenCV version

**Comment by loerss** [comment]
因该是Ubuntu18.04的问题，换了16.04就ok了

**Comment by alsosos** [comment]
好的 感谢



---Original---
From: ***@***.***&gt;
Date: Mon, Jun 7, 2021 22:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Livox-SDK/livox_mapping] Play mid40_ oudor bag, the point cloud will not move, as if there is only one frame of data. How can I solve this problem (#15)




 
因该是Ubuntu18.04的问题，换了16.04就ok了
