### ISSUE TITLE
Inaccurate result using my own indoor horizon data.

### ISSUE THREAD

**Issue by Xiangzhaohong** [Livox-SDK/livox_mapping#2]
I recorded my own indoor horizon data, which the height of the lidar is nearly 0.3m.
here is the result:
![图片](https://user-images.githubusercontent.com/35594043/88641461-d9eb6580-d0f1-11ea-8353-c644c1d7de3a.png)

and  I find that there is one place don't have odometry, so the map is very bad .

could you provide some suggestions?
Thanks!

**Comment by Livox-SDK** [comment]
Hi,

Horizon is not very suitable for use in small indoor scenes.
1. Pointcloud is not accurate in very close proximity;
2. There is a degradation problem when lidar is very close to the wall;

Thanks.
