### ISSUE TITLE
nav_msgs/Path  export

### ISSUE THREAD

**Issue by antun008** [Livox-SDK/livox_mapping#20]
hello, when I create bag file from this alghoritam:
How can i export next 3 topics to get some path which I will be able to use in another program to check the accuracy and precision of the trajectory of my livox:
topics:   /aft_loopclosure_path             1 msg     : nav_msgs/Path          
             /aft_mapped_path                367 msgs    : nav_msgs/Path          
             /aft_mapped_to_init            3677 msgs    : nav_msgs/Odometry  

Thanks for answer!

**Comment by Livox-SDK** [comment]
Hi antun008, 
substitute the bold text parameter in the launch file. "remap from="/livox/lidar" to="**/livox/lidar**"
