### ISSUE TITLE
catkin_make的时候找不到.h文件，求教

### ISSUE THREAD

**Issue by hitdezhazha** [Livox-SDK/livox_mapping#21]
![2021-03-31 11-29-41屏幕截图](https://user-images.githubusercontent.com/39644572/113086624-91ea8880-9214-11eb-9c91-116261b7d853.png)

**Comment by yhzyhzyhz** [comment]
你前面是不是还有opencv的文件找不到？如果用ubuntu apt安装的opencv4就没有旧版的头文件opencv/cv.h 把这个替换成opencv2/opencv.hpp应该就好了
