### ISSUE TITLE
Colorize pointcloud.

### ISSUE THREAD

**Issue by Mikor-mkr** [Livox-SDK/livox_mapping#23]
Hi everyone, 

I'd like to ask if it is possible to colorize the pointcloud and if yes do you have any suggestion on how to approach this ?

Thanks in advance.

**Comment by Livox-SDK** [comment]
HI Mikor-mkr,
There is an option under PointCloud2/ChannelName called intensity, if you choose that, the pointcloud could be colorized by the reflection rate of the object. 
If your aim is matching the pointcloud color with real-time environment color, some developments are required. The following link may give you some ideas: 
https://github.com/Livox-SDK/livox_camera_lidar_calibration
