### ISSUE TITLE
Loop Closure

### ISSUE THREAD

**Issue by David9696** [Livox-SDK/livox_mapping#26]
Hi,

Thanks for this great package. I have tried this package with Mid70 and it could create a decent 3D map. However, the mapping would be off when it comes to loop closure. Is there a way to execute loop closure with this package? Possible to include IMU input during mapping?

Thanks.

**Comment by Livox-SDK** [comment]
Hi David9696,

We did not contain loop closure procedure in this code. We may make some improvements in the future.
