### ISSUE TITLE
Map (corner.pcd) does not contain complete mapped area

### ISSUE THREAD

**Issue by gdebrecz** [Livox-SDK/livox_mapping#27]
Hi, 

When mapping a bit larger area (cc. more than 200 m) the corner.pcd file gets somehow cropped and only the mapped corners around the very last position are saved in the .pcd file. What is the reason of this ?

Is there any settings that would allow for mapping larger areas, in the order of c.c. 1 km ?

Thanks in advance,
Gergely

**Comment by Livox-SDK** [comment]
Hi gdebrecz,

To record the whole map,  please substitute the parameter laserCloudValidNum by laserCloudSurroundNum on line 716, 717, 718 under livox_mapping/src/laserMapping.cpp
![image](https://user-images.githubusercontent.com/45850995/121018735-5c908700-c7d1-11eb-9183-137c2f3d3cae.png)

**Comment by gdebrecz** [comment]
Thanks a a lot !
G
