### ISSUE TITLE
ROS2 version of livox mapping

### ISSUE THREAD

**Issue by hardesh-peppermint** [Livox-SDK/livox_mapping#28]
Hi, 
Thanks for open sourcing this package. I was wondering if you are going to release a ROS2 version of this package. 

TIA
Harshal

**Comment by Livox-SDK** [comment]
Hi hardesh-peppermint，

Sorry we don't have such a plan

**Comment by MAVProxyUser** [comment]
@Livox-SDK ROS1 is end of life... does this mean your Lidar support is also end of life? 
https://twitter.com/rosorg/status/1532013407435640833
![image](https://user-images.githubusercontent.com/2904396/216219345-7e9bb3db-4c83-4e0a-a77a-23c79ad24737.png)
