### ISSUE TITLE
Supporting for mid-70

### ISSUE THREAD

**Issue by lbxxdi** [Livox-SDK/livox_mapping#29]
this package support mid-70 ?? 

If yes,
1. could you please provide bag for mid-70 ( especially indoor ) ?? 
2. how fast speed while mapping ??
3. Is it slower than mid-40 For FOV coverage ??

**Comment by wzy012** [comment]
you can use mapping_mid.launch,I have tested.

**Comment by LinkChain** [comment]
打开终端1输入：roslaunch livox_mapping mapping_mid.launch
打开终端2输入：roslaunch livox_ros_driver livox_lidar.launch

**Comment by Livox-SDK** [comment]
Hi lbxxdi

Yes, please use mapping_mid.launch
1. sorry, bag file is not permitted to be provided due to the policy reason 
2. It depends on how large is the area
3. Due to the FOV of mid-70 is larger than mid-40, for scanning the same area, the speed should be faster
