### ISSUE TITLE
cant play with my own bag 

### ISSUE THREAD

**Issue by YushengWHU** [Livox-SDK/livox_mapping#3]
I successfully compiled livox_mapping package with PCL 1.9, and I recorded my own bag with horizon, however, when I tried to use it together with livox_mapping, the terminal gives me cant match livox_repub "/livox/lidar"message type, which is "livox_ros_driver::CustomMsg", but for me ,the recorded bag is "sensor_msgs::PointCloud2". Thus I modified the file a little bit, but it cant work, so how do I record the /livox/lidar topic with the specific type "livox_ros_driver::CustomMsg"

**Comment by YushengWHU** [comment]
solved, am stupid

**Comment by Alevs2R** [comment]
How you solved it? I have the same problem

**Comment by YushengWHU** [comment]
> How you solved it? I have the same problem

record your bag after
roslaunch livox_ros_driver livox_lidar_custommsg.launch
I dont remember exactly the script, so you should check out yourself, make sure that the custommsg is broadcasted.
