### ISSUE TITLE
scanRegistration.cpp文件中的465行if的作用

### ISSUE THREAD

**Issue by guojing-gj** [Livox-SDK/livox_mapping#31]
scanRegistration.cpp文件中的465行
    double cc = fabs( norm_front.dot(norm_back) / (norm_front.norm()*norm_back.norm()) );
        if(cc < 0.8){
        debugnum3++;
      }else{
        CloudFeatureFlag[i] = 0;
      }
这个if的作用是什么，为什么abs(cos(t))<0.8(t属于[37度，143度])就不是角特征点了？

**Comment by Livox-SDK** [comment]
Hi guojing-gj

这个 if 限制的是只取 (cc < 0.8) 内的点 即 属于[37度，143度] 内的点； 具体的参数并不是定死的 这个阈值是可以调的； 角特征点更倾向于90度左右的点；这个范围只是个例子
