### ISSUE TITLE
Livox_mapping for CustomMsg

### ISSUE THREAD

**Issue by lacie-life** [Livox-SDK/livox_mapping#47]
Thanks for your code. How to convert CustomMsg in livox_ros_driver for livox mapping?

**Comment by WH30** [comment]
Add 
```
  <node pkg="livox_mapping" type="livox_repub" name="livox_repub" output="screen" >
  <remap from="/livox/lidar" to="/livox/lidar" />
  </node>
```
in your lauch file as` mapping_horizon.lauch` does.

`livox_repub` convert CustomMsg to PCL2

**Comment by lacie-life** [comment]
Thanks you!!!
