### ISSUE TITLE
How to get UNIX/POSIX time stamp in the header of ROS msg

### ISSUE THREAD

**Issue by Acmece** [Livox-SDK/livox_mapping#5]
Hi, the current time of the header is counts from 0. I conjecture it is the clock of the livox. But I want to use the UNIX timestamp of the host, so as to connect livox_mapping with other modules(e.g. planning, control). I have read through the code but can not find a way to do it. Is there any hint about that?

**Comment by qianxingqx** [comment]
Hi,
  I have the same problem with you! Have you solved this problem? If you have, would you mind to share how to use the UNIX timestamp in Livox lidar?
  Thank you very much!
