### ISSUE TITLE
Save Map File not work!!

### ISSUE THREAD

**Issue by mokserpent** [Livox-SDK/livox_mapping#8]
I run the livox mapping with horizon  and set the param as "<param name="map_file_path" type="string" value="Livox_Horizon_PointCloud"/>"
,use Ctrl+C stop the process but got no saved file.
Is it need other things to do and then can save the map data??
Thx for any help...

**Comment by Livox-SDK** [comment]
Hi, you can check whether the map_file_path in the launch file is filled in correctly.

**Comment by mokserpent** [comment]
Dear SDK...>'<
I am sure I filled the file path well in the parameter section , but no any file saved after stopping the process.

**Comment by CQUTwuyanzu** [comment]
I have the same issue with you
by using  Ctrl+C stop the process but got no saved file.
after changing value=" "
<param name="map_file_path" type="string" value=" " /> 
in mapping_mid.launch      it didn't work  
did you solve this problem yet?

**Comment by mokserpent** [comment]
Sorry , the situation still , just I use Horizon not Mid..but the same
result , no file saved so far.

CQUTwuyanzu <notifications@github.com> 於 2020年11月10日 週二 下午5:16寫道：

**Comment by uhobeike** [comment]
Hello.
I know how you can solve your problem. I think this link will be helpful.
https://github.com/uhobeike/livox_mapping/blob/693fc50bc5485f5b31c1b1e354da3d83fef99b92/launch/mapping_horizon.launch#L11
↑Change ikebe to your username.

Also, as CQUTwuyanzu says, the folder must exist.
If the folder does not exist, create it as follows.

Similarly, change ikebe to your own user.
↓
ex) mkdir -p / home / ikebe / Documents / livox_pcd_data 

I think it will be generated by ctl + c.

**Comment by hitdezhazha** [comment]
> Hello.
> I know how you can solve your problem. I think this link will be helpful.
> https://github.com/uhobeike/livox_mapping/blob/693fc50bc5485f5b31c1b1e354da3d83fef99b92/launch/mapping_horizon.launch#L11
> ↑Change ikebe to your username.
> 
> Also, as CQUTwuyanzu says, the folder must exist.
> If the folder does not exist, create it as follows.
> 
> Similarly, change ikebe to your own user.
> ↓
> ex) mkdir -p / home / ikebe / Documents / livox_pcd_data
> 
> I think it will be generated by ctl + c.

Hey! thank you so much successfully solved!
