### ISSUE TITLE
How to save pcd file in livox-mapping？

### ISSUE THREAD

**Issue by zhangyingzhuangk** [Livox-SDK/livox_mapping#9]
In step 2. Build
Clone the repository and catkin_make:

    cd ~/catkin_ws/src
    git clone https://github.com/Livox-SDK/livox_mapping.git
    cd ..
    catkin_make
    source ~/catkin_ws/devel/setup.bash
Remarks:

If you want to save the pcd file please add map_file_path in launch file.

My question is how to add map_file_path in launch file，and how to save the pcd file .
Please tell more specifics about it.

**Comment by Livox-SDK** [comment]
Hi, you can select the launch file you use in the "livox_mapping/launch/" path, and write the map file path in this file.
